Update index.html
QueenterJuma/Portfolio_1 pull request #2
Opened 2022-10-29 23:08 UTC by QueenterJuma

Added works section and about me section to mobile-version branch

2022-10-29 23:35 UTC, jerryowusu requested changes
Hi @QueenterJuma 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, I've found some room for improvement that can help you accomplish a more readable/clean code and make your project look professional :sunglasses:

![soclose](https://user-images.githubusercontent.com/65233860/198856281-8a601fba-1958-4ed9-af6a-fee3d473e128.gif)


## Highlights
:heavy_check_mark: All linters are passing
:heavy_check_mark: Followed GItHub flow

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 23:35 UTC, jerryowusu commented on index.html
> +          <li><a href="">BACK END DEV</a></li>
The styling seems not to be working effectively as shown in the images below. Kindly make sure everything is working fine. The container of the projects should be aligned with grid and has the proper background image.

![Screenshot from 2022-10-29 23-15-59](https://user-images.githubusercontent.com/65233860/198856036-b11a2046-98b0-491b-83c4-25f4311b2382.png)

2022-10-29 23:35 UTC, jerryowusu commented on index.html
> +    </div>
Each card should be aligned with flex box.

2022-10-29 23:35 UTC, jerryowusu commented on index.html
> +      <div class="plc-img1" ></div>
Kindly make sure that the project images are all working well with the right size and position.

2022-10-29 23:35 UTC, jerryowusu commented on index.html
> +        <button>See Project</button>
The button should be a link a or button tag, and kindly follow the button styling: Active, Hover and Pressed (see design)

2022-10-29 23:35 UTC, jerryowusu commented on index.html
> +          <li><a href="">JAVASCRIPT</a></li>
Kindly ensure that the section has the margins (top, bottom, left, right) defined in the design,
the section should also use the font and colours (background and font) defined for the template.
Your design is currently different as shown below.

![Screenshot from 2022-10-29 23-15-59](https://user-images.githubusercontent.com/65233860/198856173-f2b0eeab-8f2e-4d30-bf46-1cf7909fc929.png)

2022-10-29 23:35 UTC, jerryowusu commented on index.html
> +              ></a>
Kindly ensure that you use the correct background image, fonts, colors, and other dimensions in order for your design to conform with the figma design. 

Your Design

![Screenshot from 2022-10-29 23-16-11](https://user-images.githubusercontent.com/65233860/198856210-2a6d35fd-08b9-439f-866c-b8ab47a0e92a.png)

2022-10-31 09:19 UTC, christianbiring1 requested changes
Hi @QueenterJuma , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/198972832-56126083-6601-4944-a8da-6bfde1050187.gif)


## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `summary`
- [ ] Good looking UI :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Updating your README and add the crucial points that are missing.
`Get started`
`That tell(shows how someone can make a copy of your repos and run it on their local computer)`
- [ ] Adding a detailed description telling what your project is about
- [ ] Giving your PR a descriptive `title`, `update index.html` doesn't link with the project.
`HINT: You can consider saying for ex: Finish mobile version` :smile: 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-31 09:19 UTC, christianbiring1 commented on index.html
> +          <li><a href="">2015</a></li>
- [ ] Kindly make sure you stick to the design as much as possible. 
- [ ] Kindly make sure you use a similar typo(`font-size, weight and color`) as the design
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/198970748-a23b5988-7c29-4627-8b0d-d32359b79b26.png)
Figma design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/198970832-1de791ff-d509-4ed0-becf-a21a2df1315c.png)

2022-10-31 09:19 UTC, christianbiring1 commented on index.html
> +        </ul>
- [ ] Kindly make sure your stack list style is similar to the style in the Figma design template.(color, typo, spacing)
![image](https://user-images.githubusercontent.com/97100091/198971205-21e0484e-f137-494c-91dc-5c7af2fc64c1.png)
Figma design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/198971478-b7b473bd-9bc8-4cc0-91fb-f76902c0f49c.png)

2022-10-31 09:19 UTC, christianbiring1 commented on index.html
> +        <button>See Project</button>
- [ ] kindly make sure you fix this overlpping
Your design :point_down: 
![Screenshot from 2022-10-31 11-06-00](https://user-images.githubusercontent.com/97100091/198971969-428e75f2-8cdc-4a74-9f9b-0f403b2443e0.png)

Figma design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/198972048-d82f3529-7a5d-47be-8ea3-a3948cd31693.png)

2022-10-31 09:19 UTC, christianbiring1 commented on index.html
> +      </div>
- [ ] Kindly make sure your elements are well positioned on the page. Consider using the same spacing (`margin, padding`) as the design in Figma. :smile: 

Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/198972388-254d30ee-dc30-4098-ae9c-553813d7a319.png)

Figma design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/198972507-b7f91320-22ab-4cdb-a197-eb513b2004cd.png)

2022-10-31 19:02 UTC, topeogunleye approved these changes
### Hi @QueenterJuma, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
* [ ]  Please check my inline comments.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-31 19:02 UTC, topeogunleye commented on style.css
> +.lang li a {
- [ ] [OPTIONAL] I kindly suggest that you make sure your stack list style is similar to the style in the Figma design template.(color, typo, spacing). The colors you use here are overriding the correct colors from `.lang li` css selector

| Your Design  | Figma Design |
| ------------- | ------------- |
| <img width="200" alt="image" src="https://user-images.githubusercontent.com/52934128/199087771-16a21c36-e7b5-412c-a9d0-2c78117c6e11.png">  | <img width="291" alt="image" src="https://user-images.githubusercontent.com/52934128/199087942-cd0a6f2f-8e98-42cb-bf0a-c2a63a9a8ac0.png">  |

2022-10-31 20:18 UTC, merged